/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.4.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MentalModelTriggerOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelTriggerOutput{}

// MentalModelTriggerOutput Trigger settings for a mental model.
type MentalModelTriggerOutput struct {
	// If true, refresh this mental model after observations consolidation (real-time mode)
	RefreshAfterConsolidation *bool `json:"refresh_after_consolidation,omitempty"`
	FactTypes []string `json:"fact_types,omitempty"`
	// If true, exclude all mental models from the reflect loop (skip search_mental_models tool).
	ExcludeMentalModels *bool `json:"exclude_mental_models,omitempty"`
	ExcludeMentalModelIds []string `json:"exclude_mental_model_ids,omitempty"`
	TagsMatch NullableString `json:"tags_match,omitempty"`
	TagGroups []MentalModelTriggerOutputTagGroupsInner `json:"tag_groups,omitempty"`
}

// NewMentalModelTriggerOutput instantiates a new MentalModelTriggerOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelTriggerOutput() *MentalModelTriggerOutput {
	this := MentalModelTriggerOutput{}
	var refreshAfterConsolidation bool = false
	this.RefreshAfterConsolidation = &refreshAfterConsolidation
	var excludeMentalModels bool = false
	this.ExcludeMentalModels = &excludeMentalModels
	return &this
}

// NewMentalModelTriggerOutputWithDefaults instantiates a new MentalModelTriggerOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelTriggerOutputWithDefaults() *MentalModelTriggerOutput {
	this := MentalModelTriggerOutput{}
	var refreshAfterConsolidation bool = false
	this.RefreshAfterConsolidation = &refreshAfterConsolidation
	var excludeMentalModels bool = false
	this.ExcludeMentalModels = &excludeMentalModels
	return &this
}

// GetRefreshAfterConsolidation returns the RefreshAfterConsolidation field value if set, zero value otherwise.
func (o *MentalModelTriggerOutput) GetRefreshAfterConsolidation() bool {
	if o == nil || IsNil(o.RefreshAfterConsolidation) {
		var ret bool
		return ret
	}
	return *o.RefreshAfterConsolidation
}

// GetRefreshAfterConsolidationOk returns a tuple with the RefreshAfterConsolidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelTriggerOutput) GetRefreshAfterConsolidationOk() (*bool, bool) {
	if o == nil || IsNil(o.RefreshAfterConsolidation) {
		return nil, false
	}
	return o.RefreshAfterConsolidation, true
}

// HasRefreshAfterConsolidation returns a boolean if a field has been set.
func (o *MentalModelTriggerOutput) HasRefreshAfterConsolidation() bool {
	if o != nil && !IsNil(o.RefreshAfterConsolidation) {
		return true
	}

	return false
}

// SetRefreshAfterConsolidation gets a reference to the given bool and assigns it to the RefreshAfterConsolidation field.
func (o *MentalModelTriggerOutput) SetRefreshAfterConsolidation(v bool) {
	o.RefreshAfterConsolidation = &v
}

// GetFactTypes returns the FactTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTriggerOutput) GetFactTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FactTypes
}

// GetFactTypesOk returns a tuple with the FactTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTriggerOutput) GetFactTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.FactTypes) {
		return nil, false
	}
	return o.FactTypes, true
}

// HasFactTypes returns a boolean if a field has been set.
func (o *MentalModelTriggerOutput) HasFactTypes() bool {
	if o != nil && !IsNil(o.FactTypes) {
		return true
	}

	return false
}

// SetFactTypes gets a reference to the given []string and assigns it to the FactTypes field.
func (o *MentalModelTriggerOutput) SetFactTypes(v []string) {
	o.FactTypes = v
}

// GetExcludeMentalModels returns the ExcludeMentalModels field value if set, zero value otherwise.
func (o *MentalModelTriggerOutput) GetExcludeMentalModels() bool {
	if o == nil || IsNil(o.ExcludeMentalModels) {
		var ret bool
		return ret
	}
	return *o.ExcludeMentalModels
}

// GetExcludeMentalModelsOk returns a tuple with the ExcludeMentalModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelTriggerOutput) GetExcludeMentalModelsOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeMentalModels) {
		return nil, false
	}
	return o.ExcludeMentalModels, true
}

// HasExcludeMentalModels returns a boolean if a field has been set.
func (o *MentalModelTriggerOutput) HasExcludeMentalModels() bool {
	if o != nil && !IsNil(o.ExcludeMentalModels) {
		return true
	}

	return false
}

// SetExcludeMentalModels gets a reference to the given bool and assigns it to the ExcludeMentalModels field.
func (o *MentalModelTriggerOutput) SetExcludeMentalModels(v bool) {
	o.ExcludeMentalModels = &v
}

// GetExcludeMentalModelIds returns the ExcludeMentalModelIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTriggerOutput) GetExcludeMentalModelIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExcludeMentalModelIds
}

// GetExcludeMentalModelIdsOk returns a tuple with the ExcludeMentalModelIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTriggerOutput) GetExcludeMentalModelIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeMentalModelIds) {
		return nil, false
	}
	return o.ExcludeMentalModelIds, true
}

// HasExcludeMentalModelIds returns a boolean if a field has been set.
func (o *MentalModelTriggerOutput) HasExcludeMentalModelIds() bool {
	if o != nil && !IsNil(o.ExcludeMentalModelIds) {
		return true
	}

	return false
}

// SetExcludeMentalModelIds gets a reference to the given []string and assigns it to the ExcludeMentalModelIds field.
func (o *MentalModelTriggerOutput) SetExcludeMentalModelIds(v []string) {
	o.ExcludeMentalModelIds = v
}

// GetTagsMatch returns the TagsMatch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTriggerOutput) GetTagsMatch() string {
	if o == nil || IsNil(o.TagsMatch.Get()) {
		var ret string
		return ret
	}
	return *o.TagsMatch.Get()
}

// GetTagsMatchOk returns a tuple with the TagsMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTriggerOutput) GetTagsMatchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagsMatch.Get(), o.TagsMatch.IsSet()
}

// HasTagsMatch returns a boolean if a field has been set.
func (o *MentalModelTriggerOutput) HasTagsMatch() bool {
	if o != nil && o.TagsMatch.IsSet() {
		return true
	}

	return false
}

// SetTagsMatch gets a reference to the given NullableString and assigns it to the TagsMatch field.
func (o *MentalModelTriggerOutput) SetTagsMatch(v string) {
	o.TagsMatch.Set(&v)
}
// SetTagsMatchNil sets the value for TagsMatch to be an explicit nil
func (o *MentalModelTriggerOutput) SetTagsMatchNil() {
	o.TagsMatch.Set(nil)
}

// UnsetTagsMatch ensures that no value is present for TagsMatch, not even an explicit nil
func (o *MentalModelTriggerOutput) UnsetTagsMatch() {
	o.TagsMatch.Unset()
}

// GetTagGroups returns the TagGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTriggerOutput) GetTagGroups() []MentalModelTriggerOutputTagGroupsInner {
	if o == nil {
		var ret []MentalModelTriggerOutputTagGroupsInner
		return ret
	}
	return o.TagGroups
}

// GetTagGroupsOk returns a tuple with the TagGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTriggerOutput) GetTagGroupsOk() ([]MentalModelTriggerOutputTagGroupsInner, bool) {
	if o == nil || IsNil(o.TagGroups) {
		return nil, false
	}
	return o.TagGroups, true
}

// HasTagGroups returns a boolean if a field has been set.
func (o *MentalModelTriggerOutput) HasTagGroups() bool {
	if o != nil && !IsNil(o.TagGroups) {
		return true
	}

	return false
}

// SetTagGroups gets a reference to the given []MentalModelTriggerOutputTagGroupsInner and assigns it to the TagGroups field.
func (o *MentalModelTriggerOutput) SetTagGroups(v []MentalModelTriggerOutputTagGroupsInner) {
	o.TagGroups = v
}

func (o MentalModelTriggerOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelTriggerOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefreshAfterConsolidation) {
		toSerialize["refresh_after_consolidation"] = o.RefreshAfterConsolidation
	}
	if o.FactTypes != nil {
		toSerialize["fact_types"] = o.FactTypes
	}
	if !IsNil(o.ExcludeMentalModels) {
		toSerialize["exclude_mental_models"] = o.ExcludeMentalModels
	}
	if o.ExcludeMentalModelIds != nil {
		toSerialize["exclude_mental_model_ids"] = o.ExcludeMentalModelIds
	}
	if o.TagsMatch.IsSet() {
		toSerialize["tags_match"] = o.TagsMatch.Get()
	}
	if o.TagGroups != nil {
		toSerialize["tag_groups"] = o.TagGroups
	}
	return toSerialize, nil
}

type NullableMentalModelTriggerOutput struct {
	value *MentalModelTriggerOutput
	isSet bool
}

func (v NullableMentalModelTriggerOutput) Get() *MentalModelTriggerOutput {
	return v.value
}

func (v *NullableMentalModelTriggerOutput) Set(val *MentalModelTriggerOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelTriggerOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelTriggerOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelTriggerOutput(val *MentalModelTriggerOutput) *NullableMentalModelTriggerOutput {
	return &NullableMentalModelTriggerOutput{value: val, isSet: true}
}

func (v NullableMentalModelTriggerOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelTriggerOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


